Q1 (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 

In [2]:
import numpy as np
import math
arr = np.array([1,2,3,4,5,6])
print('Initial Array:',arr)

n = len(arr)
n1 = math.floor(n/2)

for i in range(n1):
  arr[i], arr[n-i-1] = arr[n-i-1], arr[i]

# arr = np.flipud(arr)
print('Reversed Array:',arr)


Initial Array: [1 2 3 4 5 6]
Reversed Array: [6 5 4 3 2 1]


Q1 (b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods

In [3]:
import numpy as np
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
print('Initial Array:',array1)
array1 = array1.flatten()
print('Flattened Array:',array1)

Initial Array: [[1 2 3]
 [2 4 5]
 [1 2 3]]
Flattened Array: [1 2 3 2 4 5 1 2 3]


Q1 (c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [4]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print('Array 1: ', arr1)
print('\nArray 2: ', arr2)

comparison = arr1 == arr2
if(comparison.all()):
  print('\nArrays are equal')
# print('\n',comparison.all())
 
# print("arr1 > arr2")
# print(np.greater(arr1, arr2))
 
# print("arr1 >= arr2")
# print(np.greater_equal(arr1, arr2))
 
# print("arr1 < arr2")
# print(np.less(arr1, arr2))
 
# print("arr1 <= arr2")
# print(np.less_equal(arr1, arr2))


Array 1:  [[1 2]
 [3 4]]

Array 2:  [[1 2]
 [3 4]]

Arrays are equal


Q1 (d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [5]:
import numpy
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
maxcount_x = 0;
el_max_x = 0;
for i in range(0,10):
  count_x = 0
  indices_x = []
  for j in range(0,10):
    if(x[i]==x[j]):
      count_x += 1
      indices_x = np.append(indices_x,j)
      if(count_x > maxcount_x):
        maxcount_x = count_x
        el_max_x = x[i]
print('Highest frequency element in array X is:',el_max_x,'with frequency:',maxcount_x,'and indices:',indices_x)

maxcount_y = 0
el_max_y = 0
for k in range(0,10):
  count_y = 0
  indices_y = []
  for l in range(0,10):
    if(y[k]==y[l]):
      count_y += 1
      indices_y = np.append(indices_y,l)
      if(count_y > maxcount_y):
        maxcount_y = count_y
        el_max_y = y[k]
print('Highest frequency element in array Y is:',el_max_y,'with frequency:',maxcount_y,'and indices:',indices_y)


Highest frequency element in array X is: 1 with frequency: 5 and indices: [0. 5. 7. 8. 9.]
Highest frequency element in array Y is: 1 with frequency: 3 and indices: [4. 8. 9.]


Q1 (e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise

In [6]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum = 0
for i in range(0,3):
  for j in range(0,3):
    sum += gfg[i,j]
print('Sum of all elements of the matrix:',sum)
print('\n')

sum = 0
row = 1
while row < 4:
  for i in range(0,row):
    for j in range(0,3):
      sum += gfg[i,j]
    print('Sum of row',row,'is:',sum)
    sum = 0
    row +=1
print('\n')

sum = 0
col = 1
while col < 4:
  for i in range(0,3):
    for j in range(0,col):
      sum += gfg[i,j]
    print('Sum of col',col,'is:',sum)
    sum = 0
    col +=1

Sum of all elements of the matrix: 45


Sum of row 1 is: 14
Sum of row 2 is: 14
Sum of row 3 is: 16


Sum of col 1 is: 4
Sum of col 2 is: 15
Sum of col 3 is: 15


Q1 (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

In [7]:
import numpy as np
from numpy import linalg as la
A = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print('A is: ',A)

sum = 0
for i in range(0,3):
  for j in range(0,3):
    if(i==j):
      sum += A[i,j]
print('\nSum of all diagonal elements of the matrix:',sum)

eig_val,eig_vec = la.eig(A)
print('\nEigen values of matrix are: ',eig_val)
print('\nEigen vector of matrix is: ',eig_vec)

inv_matrix = la.inv(A);
print('\nInverse of matrix A is: ',inv_matrix)

det_matrix = la.det(A)
print('\nDeterminent of matrix A is:',det_matrix)

A is:  [[55 25 15]
 [30 44  2]
 [11 45 77]]

Sum of all diagonal elements of the matrix: 176

Eigen values of matrix are:  [98.16835147 28.097044   49.73460452]

Eigen vector of matrix is:  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

Inverse of matrix A is:  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

Determinent of matrix A is: 137180.0000000001


Q1 (g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [8]:
import numpy as np
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
mul_matrix = [[0,0],[0,0]]

for i in range(len(p)):
    for j in range(len(q[0])):
        for k in range(len(q)):
            mul_matrix[i][j] += p[i][k] * q[k][j]
print('Multiplied matrices:',mul_matrix)

cov_p = np.cov(p)
print('\nCovariance of matrix P:',cov_p)
cov_q = np.cov(q)
print('\nCovariance of matrix P:',cov_p)

p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
mul_matrix = [[0,0],[0,0]]

mul_matrix = np.dot(p,q)
print('Multiplied matrices:',mul_matrix)

p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
p = p.flatten()
q = q.flatten()

cov_p = np.cov(p)
print('\nCovariance of matrix P:',cov_p)
cov_q = np.cov(q)
print('\nCovariance of matrix P:',cov_p)




Multiplied matrices: [[16, 19], [26, 31]]

Covariance of matrix P: [[0.5 0.5]
 [0.5 0.5]]

Covariance of matrix P: [[0.5 0.5]
 [0.5 0.5]]
Multiplied matrices: [[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance of matrix P: 2.166666666666667

Covariance of matrix P: 2.166666666666667


Q1 (h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), find inner, outer and cartesian product?

In [9]:
import numpy as np 
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

x_trans = np.zeros((3,2),dtype=int)
y_trans = np.zeros((3,2),dtype=int)
# q = np.zeros((3,2),dtype=int)

# transpose of array x
for i in range(len(x[0])):
  for j in range(len(x)):
    x_trans[i][j]= x[j][i]

# transpose of array y
for i in range(len(y[0])):
  for j in range(len(y)):
    y_trans[i][j]= y[j][i]  

inner_pro = [[0,0,0],[0,0,0]]
inner_pro = np.dot(x_trans,y)
print('Inner product:',inner_pro)

outer_pro = [[0,0,0],[0,0,0]]
outer_pro = np.dot(x,y_trans)
print('Outer product:',outer_pro)

q = np.zeros((3,2),dtype=int)

cartesian_pro = [[0,0,0],[0,0,0]]
cartesian_pro = np.transpose([np.tile(x, len(y)),np.repeat(y,len(x))])
print('Cartesian product:',cartesian_pro)




Inner product: [[ 17  40   9]
 [ 13  35   6]
 [ 49 110  27]]
Outer product: [[17 52]
 [13 62]]
Cartesian product: [array([[2, 3, 4, 2, 3, 4],
        [3, 2, 9, 3, 2, 9]])
 array([ 1,  1,  5,  5,  0,  0,  5,  5, 10, 10,  3,  3])]


c:\Users\parth\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)


Q2) (a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each      column, for each row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row

In [10]:
import numpy as np
import math
import statistics as st
array = np.array([[1, -2, 3],[-4, 5, -6]])
# array = np.abs(array)
# print('Absolute array is: ',array)

print('\nPart (i)')
for i in range(0,2):
  for j in range(0,3):
    print(np.abs(array[i][j]))
print('\nPart (ii)')

array = array.flatten()

print('(Percentile for each row)')

row = 0
while row < 3:
  per_25 = np.percentile(array[row],25)
  print('25th Percentile of Flattened array for row',row+1,'is:',per_25)
  row += 1
print('\n')

row = 0
while row < 3:
  per_50 = np.percentile(array[row],50)
  print('50th Percentile of Flattened array for row',row+1,'is:',per_50)
  row += 1
print('\n')

row = 0
while row < 3:
  per_75 = np.percentile(array[row],75)
  print('75th Percentile of Flattened array for row',row+1,'is:',per_75)
  row += 1
print('\n')

array = np.array([[1, -2, 3],[-4, 5, -6]])
arr_trans = np.zeros((3,2),dtype=int)
for i in range (len(array[0])):
  for j in range(len(array)):
    arr_trans[i][j]= array[j][i] 

print('\n(Percentile for each Column)')

row = 0
while row < 3:
  per_25_col = np.percentile(arr_trans[row],25)
  print('25th Percentile of Flattened array for col',row+1,'is:',per_25_col)
  row += 1
print('\n')

row = 0
while row < 3:
  per_50_col = np.percentile(arr_trans[row],50)
  print('50th Percentile of Flattened array for col',row+1,'is:',per_50_col)
  row += 1
print('\n')    

row = 0
while row < 3:
  per_75_col = np.percentile(arr_trans[row],75)
  print('75th Percentile of Flattened array for col',row+1,'is:',per_75_col)
  row += 1

print('\nPart (iii)')
# sum = 0
# for i in range(len(arr)):
#   for j in range(len(arr[0])):
#     sum += arr[i][j]
# mean = sum/len(arr)
# print()  

# arr = np.array([[1, -2, 3],[-4, 5, -6]])

print('(Mean row-wise)')
sum = 0
mean = 0
i = 0
while i < len(array):
  for j in range(len(array[0])):
    sum += array[i][j]
  mean = sum/len(array[0])
  print('Mean of row',i+1,'is:',mean)
  i += 1

print('\n(Mean column-wise)')
sum = 0
mean = 0
i = 0
while i < len(arr_trans):
  for j in range(len(arr_trans[0])):
    sum += arr_trans[i][j]
  mean = sum/len(arr_trans[0])
  print('Mean of column',i+1,'is:',mean)
  i += 1

def arr_sort(arr):
  for i in range(len(arr)-1):
    for j in range(i+1,len(arr)):
      if(arr[j] < arr[i]):
        temp=arr[i]
        arr[i]=arr[j]
        arr[j]=temp
  return arr

print('\n(Median row-wise)')
for i in range(len(array)):
  med_arr = []
  for j in range(len(array[0])):
    med_arr.append(array[i][j])
  med_arr = arr_sort(med_arr)
  length = len(med_arr)
  med = 0
  med = math.floor(1/2*(length+1))
  print('Median of row',i+1,'of array is:',med_arr[med])

print('\n(Median column-wise)')
for i in range(len(arr_trans)):
  med_arr = []
  for j in range(len(arr_trans[0])):
    med_arr.append(arr_trans[i][j])
  med_arr = arr_sort(med_arr)
  length = len(med_arr)
  med = 0
  med = math.floor(1/2*(length+1))
  print('Median of column',i+1,'of array is:',med_arr[med])

print('\nStandard Devaition for the array is:',st.stdev(arr))


Part (i)
1
2
3
4
5
6

Part (ii)
(Percentile for each row)
25th Percentile of Flattened array for row 1 is: 1.0
25th Percentile of Flattened array for row 2 is: -2.0
25th Percentile of Flattened array for row 3 is: 3.0


50th Percentile of Flattened array for row 1 is: 1.0
50th Percentile of Flattened array for row 2 is: -2.0
50th Percentile of Flattened array for row 3 is: 3.0


75th Percentile of Flattened array for row 1 is: 1.0
75th Percentile of Flattened array for row 2 is: -2.0
75th Percentile of Flattened array for row 3 is: 3.0



(Percentile for each Column)
25th Percentile of Flattened array for col 1 is: -2.75
25th Percentile of Flattened array for col 2 is: -0.25
25th Percentile of Flattened array for col 3 is: -3.75


50th Percentile of Flattened array for col 1 is: -1.5
50th Percentile of Flattened array for col 2 is: 1.5
50th Percentile of Flattened array for col 3 is: -1.5


75th Percentile of Flattened array for col 1 is: -0.25
75th Percentile of Flattened array for c

Q2) (b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values

In [11]:
import numpy as np
import math

a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
b = []
for i in range(len(a)):
  b.append(math.floor(a[i]))
print('Array with floor values:',b)

b = []
for i in range(len(a)):
  b.append(math.ceil(a[i]))
print('Array with Ceil values:',b)

b = []
for i in range(len(a)):
  b.append(math.trunc(a[i]))
print('Array with Truncate values:',b)

b = []
for i in range(len(a)):
  b.append(round(a[i],2))
print('Array with Rounded values:',b)


Array with floor values: [-2, -2, -1, 0, 1, 1, 3]
Array with Ceil values: [-1, -1, 0, 1, 2, 2, 3]
Array with Truncate values: [-1, -1, 0, 0, 1, 1, 3]
Array with Rounded values: [-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0]


Q3) (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements

In [12]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
def arr_sort(arr):
  for i in range(len(arr)-1):
    for j in range(i+1,len(arr)):
      if(arr[j] < arr[i]):
        temp=arr[i]
        arr[i]=arr[j]
        arr[j]=temp
  return arr 

sorted_arr = arr_sort(array)
print('Sorted array is: ',sorted_arr)     

small_ele = []
for i in range(4):
  small_ele.append(sorted_arr[i])
print('Smallest four elements are: ',small_ele)

large_ele = []
for i in range(5,0,-1):
  large_ele.append(sorted_arr[i])
print('Largest five elements are: ',large_ele)

Sorted array is:  [ 10  16  16  52  54  62 453]
Smallest four elements are:  [10, 16, 16, 52]
Largest five elements are:  [62, 54, 52, 16, 16]


Q3) b)

In [1]:
import numpy as np
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

result = array[array== array.astype(int)]
print('Integer elements only are:',result)
result = array[array != array.astype(int)]
print('Float elements only are:',result)

Integer elements only are: [1. 2. 3. 2.]
Float elements only are: [1.2 2.2]
